version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: ims-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 211119
      MYSQL_DATABASE: imsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 211119
    ports:
      - "3307:3306"
    networks:
      - ims-network

  app:
    build: .
    container_name: inventory-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ims-db:3307/imsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 211119
    ports:
      - "8080:8080"
    networks:
      - ims-network

networks:
  ims-network:
    driver: bridge
