version: '3.8'

services:
  mysql-db:
    image: mysql
    container_name: mysqldb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 211119
      MYSQL_DATABASE: imsdb
    ports:
      - "3308:3306"
    networks:
      - spring_mysql

  spring-boot-app:
    container_name: ims_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: 211119
      MYSQL_PORT: 3306
    networks:
      - spring_mysql

networks:
  spring_mysql:
    driver: bridge
